#ifndef __cmdline__
#define __cmdline__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -c: scan codes to react to */
  char codeP;
  int *code;
  int codeC;
  /***** -e: run command on negative(0) oder positive(1) edge */
  char edgeP;
  int *edge;
  int edgeC;
  /***** -cmd: command to execute */
  char commandP;
  char* *command;
  int commandC;
  /***** -fg: run in foreground do not daemonize */
  char foregroundP;
  /***** -d: run in debug mode (implies foreground) */
  char debugP;
  /***** -q: query available devices */
  char queryP;
  /***** -dev: device to use for input */
  char deviceP;
  char* device;
  int deviceC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

